version: '3.8'
services:
  backend:
    build: ./dokodine-backend
    ports:
      - 8000:8000
    volumes:
      - ./dokodine-backend/app:/code/app

  frontend:
    build: ./dokodine-frontend
    ports:
      - "3000:3000"
    volumes:
      # - ./dokodine-frontend/src:/app/src
      - ./dokodine-frontend/public:/app/public
    depends_on:
      - backend